package batchsystem

import (
	"context"
	"net/http"

	commonIL "github.com/intertwin-eu/interlink/pkg/interlink"
	v1 "k8s.io/api/core/v1"
)

// BatchSystem defines the interface that all batch system implementations must satisfy.
// This abstraction allows the plugin to support multiple batch schedulers (SLURM, PBS, LSF, etc.)
// by implementing a common set of operations for pod lifecycle management.
type BatchSystem interface {
	// Create submits a new pod to the batch system and returns the job identifier.
	// It translates Kubernetes pod specifications into batch system job scripts,
	// handling resource limits, environment variables, volume mounts, and container probes.
	Create(ctx context.Context, pod commonIL.RetrievedPodData) (CreateResult, error)

	// Delete cancels a running batch job and cleans up associated resources.
	// It removes job ID mappings and deletes all associated files (scripts, logs, mounted data).
	Delete(ctx context.Context, pod *v1.Pod) error

	// Status retrieves the current status of one or more pods from the batch system.
	// It queries job states and translates them into Kubernetes pod/container statuses,
	// mapping batch system states (e.g., SLURM's R, PD, CD) to Kubernetes states
	// (Running, Waiting, Terminated).
	Status(ctx context.Context, pods []*v1.Pod) ([]commonIL.PodStatus, error)

	// GetLogs retrieves stdout/stderr logs for containers in a pod.
	// It reads log files generated by the batch job execution and returns them
	// as byte arrays, optionally supporting log streaming and tail operations.
	GetLogs(ctx context.Context, pod *v1.Pod, containerName string, opts LogOptions) ([]byte, error)

	// GetSystemInfo returns information about the batch system cluster state.
	// This may include partition information, node states, resource availability,
	// or other system-level metadata specific to the batch scheduler.
	GetSystemInfo(ctx context.Context) (string, error)

	// Initialize performs any necessary setup for the batch system handler.
	// This may include creating working directories, loading saved state,
	// or establishing connections to the batch scheduler.
	Initialize(ctx context.Context) error
}

// HTTPHandler wraps a BatchSystem to provide HTTP endpoints for the plugin API.
// It implements the interLink plugin interface by exposing Create, Delete, Status,
// GetLogs, and SystemInfo operations over HTTP.
type HTTPHandler interface {
	SubmitHandler(w http.ResponseWriter, r *http.Request)
	StopHandler(w http.ResponseWriter, r *http.Request)
	StatusHandler(w http.ResponseWriter, r *http.Request)
	GetLogsHandler(w http.ResponseWriter, r *http.Request)
	SystemInfoHandler(w http.ResponseWriter, r *http.Request)
}
